edge-tts --voice zh-CN-YunyangNeural --text '为了看日出，我常常早起。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_00_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '那时天还没有大亮，周围非常冷清，船上只有机器的响声。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_01_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '天空还是一片浅蓝，颜色很浅。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_02_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '转眼间天边出现了一道红霞，慢慢地在扩大它的范围，加强它的亮光。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_03_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '我知道太阳要从天边升起来了，便目不转睛地望着那里。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_04_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '果然过了一会儿，在那个地方出现了太阳的小半边脸，红是真红，却没有亮光。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_05_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '这个太阳好像负着重荷似的一步一步，慢慢地努力上升，到了最后，终于冲破了云霞，完全跳出了海面，颜色红的非常可爱。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_06_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '一霎那间，这个深红的圆东西，忽然间发出了夺目的亮光，射得人眼睛发痛，它旁边的云片也忽然有了光彩。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_07_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '有时太阳走进了云堆中，它的光线却从云里射下来，直射到水面上。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_08_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '这时候要分辨出哪里是水，哪里是天，倒也不容易，因为我就只看见一片灿烂的亮光。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_09_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '有时天边有黑云，而且云片很厚，太阳出来，人眼还看不见。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_10_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '然而太阳在黑云里放射的光芒，透过黑云的重围，替黑云镶了一道发光的金边。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_11_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '后来太阳才慢慢地冲出重围，出现在天空，甚至把黑云也染成了紫色或者红色。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_12_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '这时候发亮的不仅是太阳、云和海水，连我自己也成了明亮的了。' --write-media /home/aistudio/edge-tts/mp3/yunyang/haishangrichu_13_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '燕子去了，有再来的时候；杨柳枯了，有再青的时候；桃花谢了，有再开的时候。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_00_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '但是，聪明的，你告诉我，我们的日子为什么一去不复返呢？——是有人偷了他们罢：那是谁？又藏在何处呢？是他们自己逃走了罢：现在又到了哪里呢？我不知道他们给了我多少日子；但我的手确乎是渐渐空虚了。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_01_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '在默默里算着，八千多日子已经从我手中溜去；像针尖上一滴水滴在大海里，我的日子滴在时间的流里，没有声音，也没有影子。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_02_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '我不禁头涔涔而泪潸潸了。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_03_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '去的尽管去了，来的尽管来着；去来的中间，又怎样地匆匆呢？早上我起来的时候，小屋里射进两三方斜斜的太阳。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_04_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '太阳他有脚啊，轻轻悄悄地挪移了；我也茫茫然跟着旋转。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_05_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '于是——洗手的时候，日子从水盆里过去；吃饭的时候，日子从饭碗里过去；默默时，便从凝然的双眼前过去。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_06_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '我觉察他去的匆匆了，伸出手遮挽时，他又从遮挽着的手边过去，天黑时，我躺在床上，他便伶伶俐俐地从我身上跨过，从我脚边飞去了。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_07_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '等我睁开眼和太阳再见，这算又溜走了一日。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_08_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '我掩着面叹息。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_09_yunyang.mp3
edge-tts --voice zh-CN-YunyangNeural --text '但是新来的日子的影儿又开始在叹息里闪过了。' --write-media /home/aistudio/edge-tts/mp3/yunyang/congcong_10_yunyang.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '为了看日出，我常常早起。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_00_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '那时天还没有大亮，周围非常冷清，船上只有机器的响声。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_01_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '天空还是一片浅蓝，颜色很浅。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_02_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '转眼间天边出现了一道红霞，慢慢地在扩大它的范围，加强它的亮光。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_03_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '我知道太阳要从天边升起来了，便目不转睛地望着那里。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_04_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '果然过了一会儿，在那个地方出现了太阳的小半边脸，红是真红，却没有亮光。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_05_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '这个太阳好像负着重荷似的一步一步，慢慢地努力上升，到了最后，终于冲破了云霞，完全跳出了海面，颜色红的非常可爱。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_06_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '一霎那间，这个深红的圆东西，忽然间发出了夺目的亮光，射得人眼睛发痛，它旁边的云片也忽然有了光彩。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_07_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '有时太阳走进了云堆中，它的光线却从云里射下来，直射到水面上。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_08_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '这时候要分辨出哪里是水，哪里是天，倒也不容易，因为我就只看见一片灿烂的亮光。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_09_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '有时天边有黑云，而且云片很厚，太阳出来，人眼还看不见。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_10_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '然而太阳在黑云里放射的光芒，透过黑云的重围，替黑云镶了一道发光的金边。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_11_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '后来太阳才慢慢地冲出重围，出现在天空，甚至把黑云也染成了紫色或者红色。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_12_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '这时候发亮的不仅是太阳、云和海水，连我自己也成了明亮的了。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/haishangrichu_13_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '燕子去了，有再来的时候；杨柳枯了，有再青的时候；桃花谢了，有再开的时候。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_00_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '但是，聪明的，你告诉我，我们的日子为什么一去不复返呢？——是有人偷了他们罢：那是谁？又藏在何处呢？是他们自己逃走了罢：现在又到了哪里呢？我不知道他们给了我多少日子；但我的手确乎是渐渐空虚了。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_01_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '在默默里算着，八千多日子已经从我手中溜去；像针尖上一滴水滴在大海里，我的日子滴在时间的流里，没有声音，也没有影子。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_02_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '我不禁头涔涔而泪潸潸了。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_03_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '去的尽管去了，来的尽管来着；去来的中间，又怎样地匆匆呢？早上我起来的时候，小屋里射进两三方斜斜的太阳。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_04_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '太阳他有脚啊，轻轻悄悄地挪移了；我也茫茫然跟着旋转。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_05_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '于是——洗手的时候，日子从水盆里过去；吃饭的时候，日子从饭碗里过去；默默时，便从凝然的双眼前过去。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_06_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '我觉察他去的匆匆了，伸出手遮挽时，他又从遮挽着的手边过去，天黑时，我躺在床上，他便伶伶俐俐地从我身上跨过，从我脚边飞去了。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_07_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '等我睁开眼和太阳再见，这算又溜走了一日。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_08_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '我掩着面叹息。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_09_xiaoxiao.mp3
edge-tts --voice zh-CN-XiaoxiaoNeural --text '但是新来的日子的影儿又开始在叹息里闪过了。' --write-media /home/aistudio/edge-tts/mp3/xiaoxiao/congcong_10_xiaoxiao.mp3
